Repository 2024-KSEB-HealthCare-Youth/BE, pull requests merged in 2024-07, with the labels that each got.

#4 feat: 디렉토리 구조 및 엔티티 생성
  build.gradle
  src/main/java/com/keb/fmhj/comment/domain/Comment.java
  src/main/java/com/keb/fmhj/comment/domain/repository/CommentRepository.java
  src/main/java/com/keb/fmhj/comment/presentaion/CommentController.java
  src/main/java/com/keb/fmhj/comment/service/CommentService.java
  src/main/java/com/keb/fmhj/global/BaseTimeEntity.java
  src/main/java/com/keb/fmhj/item/domain/Category.java
  src/main/java/com/keb/fmhj/item/domain/Item.java
  src/main/java/com/keb/fmhj/item/domain/repository/ItemRepository.java
  src/main/java/com/keb/fmhj/item/presentaion/ItemController.java
  src/main/java/com/keb/fmhj/item/service/ItemService.java
  src/main/java/com/keb/fmhj/like/domain/Like.java
  src/main/java/com/keb/fmhj/like/domain/repository/LikeRepository.java
  src/main/java/com/keb/fmhj/like/presentaion/LikeController.java
  src/main/java/com/keb/fmhj/like/service/LikeService.java
  src/main/java/com/keb/fmhj/member/domain/Gender.java
  src/main/java/com/keb/fmhj/member/domain/Member.java
  src/main/java/com/keb/fmhj/member/domain/repository/MemberRepository.java
  src/main/java/com/keb/fmhj/member/presentaion/MemberController.java
  src/main/java/com/keb/fmhj/member/service/MemberService.java
  src/main/java/com/keb/fmhj/post/domain/Category.java
  src/main/java/com/keb/fmhj/post/domain/Post.java
  src/main/java/com/keb/fmhj/post/domain/repository/PostRepository.java
  src/main/java/com/keb/fmhj/post/presentaion/PostController.java
  src/main/java/com/keb/fmhj/post/service/PostService.java
  src/main/java/com/keb/fmhj/result/domain/Result.java
  src/main/java/com/keb/fmhj/result/domain/repository/ResultRepository.java
  src/main/java/com/keb/fmhj/result/presentaion/ResultController.java
  src/main/java/com/keb/fmhj/result/service/ResultService.java
  src/main/java/com/keb/fmhj/resultItem/Service/ResultItemService.java
  src/main/java/com/keb/fmhj/resultItem/domain/ResultItem.java
  src/main/java/com/keb/fmhj/resultItem/domain/repository/ResultItemRepository.java
  src/main/java/com/keb/fmhj/resultItem/presentation/ResultItemController.java
Labels: ⚙️ Chore, 🏷️ Database, 🌟 Feature

#9 refactor: 엔티티 매핑 관계 수정 - #3
  src/main/java/com/keb/fmhj/FmhjApplication.java
  src/main/java/com/keb/fmhj/item/domain/Item.java
  src/main/java/com/keb/fmhj/result/domain/Result.java
  src/main/resources/application.yml
Labels: ⚙️ Chore, ♻️ Refactor

#12 도커 환경 세팅
  Dockerfile
  docker-compose.yml
Labels: ⚙️ Chore, 🌍 Infrastructure

#13 refator: 도커 수정
  docker-compose.yml
Labels: ⚙️ Chore, 🌍 Infrastructure, ♻️ Refactor

#14 swagger 설정 파일 추가 및 docker 설정 간소화
  build.gradle
  docker-compose.yml
  src/main/java/com/keb/fmhj/global/config/SecurityConfig.java
  src/main/java/com/keb/fmhj/global/config/SwaggerConfig.java
  src/main/java/com/keb/fmhj/member/domain/repository/MemberRepository.java
  src/main/java/com/keb/fmhj/member/presentaion/MemberController.java
  src/main/resources/application.yml
Labels: 📃 Docs, ⚙️ Chore, 🌍 Infrastructure, ♻️ Refactor

#20 회원 오류 수정 및 회원 수정, 삭제 기능 추가 - #17
  build.gradle
  src/main/java/com/keb/fmhj/member/domain/repository/MemberRepository.java
  src/main/java/com/keb/fmhj/member/presentaion/MemberDeleteController.java
  src/main/java/com/keb/fmhj/member/presentaion/MemberJoinController.java
  src/main/java/com/keb/fmhj/member/presentaion/MemberSearchController.java
  src/main/java/com/keb/fmhj/member/presentaion/MemberUpdateController.java
  src/main/java/com/keb/fmhj/member/service/MemberDeleteService.java
  src/main/java/com/keb/fmhj/member/service/MemberJoinService.java
  src/main/java/com/keb/fmhj/member/service/MemberUpdateService.java
Labels: 🐞 BugFix, 🌟 Feature

#22 도커 파일 수정
  docker-compose.yml
Labels: 🌍 Infrastructure, ♻️ Refactor

#23 refactor: docker 파일 수정
  src/main/resources/application.yml
Labels: 🌍 Infrastructure, ♻️ Refactor

#24 refactor: docker 파일 수정 - #21
  docker-compose.yml
Labels: 🌍 Infrastructure, ♻️ Refactor

#25 refactor: docker 파일 수정 - #21
  Dockerfile
Labels: 🌍 Infrastructure, ♻️ Refactor
